meta:
    name: '&cTest quest'
    description: |
        This is a test quest.

requirements: []
triggers: []

stages:
    entry:
        script: []
        triggers: []
    wheat:
        script: []
        triggers: []
    eggs:
        script: []
        triggers: []
    dirk:
        script: []
        triggers: []
    milk:
        script: []
        triggers: []
    complete:
        script: []
        triggers: []
    cancel:
        script: []
        triggers: []
