# citiznes ID
id: 2

# NPC name
name: '&6Blacksmith'

click:
    - gear_dislike
    - gear
    - conversation

options:
    reason:
        sent:
            display: '&2innkeeper'
            dialog: response_innkeeper
        gear:
            display: '&2gear'
            dialog: response_gear
    reason_dislike:
        sent:
            display: '&2innkeeper'
            dialog: response_innkeeper_dislike
        gear:
            display: '&2gear'
            dialog: response_gear
    looking:
        sarcastic:
            display: '&6what else?'
            dialog: response_sarcastic
        respectfull:
            display: '&2yes sir'
            dialog: response_gear
    looking_dislike:
        sarcastic:
            display: '&6what else?'
            dialog: response_sarcastic_dislike
        respectfull:
            display: '&2yes sir'
            dialog: response_gear
    gear_choice:
        sword:
            display: '&2sword'
            dialog: response_sword
        bow:
            display: '&2bow'
            dialog: response_bow
dialogs:
    gear_dislike:
        requirements: 
        - quest intro gear
        - flag innkeeper_dislike > 0
        script:
        - 0 out Hello there, what can I do for you?
        - 5 option reason_dislike
    gear:
        requirements: 
        - quest intro gear
        script:
        - 0 out Hello there, what can I do for you?
        - 5 option reason
    response_innkeeper_dislike:
        script:
        - 0 me The innkeeper sent me.
        - 20 out And I think that means that you are looking for some gear?
        - 0 option looking_dislike   
    response_innkeeper:
        script:
        - 0 me The innkeeper sent me.
        - 20 out And I think that means that you are looking for some gear?
        - 0 option looking   
    response_sarcastic_dislike:
        script:
        - 0 me What else?
        - 20 out I can see why the innkeeper doesn't like you, but I have some gear left over for people such as yourself...
        - 0 zap dislike_gear
    response_sarcastic:
        script:
        - 0 me What else?
        - 20 out Hmmm, I would appreciate it if you could be a little less sarcastic, but I have some gear left over for people such as yourself...
        - 0 zap dislike_gear
    dislike_gear:
        script:
        - 20 out I found a old bow and a rusty sword, you can chose which piece of trash you want.
        - 0 option gear_choice
    response_gear:
        script: 
        - 0 out I think that I might have some gear that you can take. I found a bow and an old sword, you can chose which of those you want.
        - 0 option gear_choice
    response_bow:
        script:
        - 0 me I would prefer the bow.
        - 0 item add _stick_and_string 1
        - 0 quest intro complete
    response_sword:
        script:
        - 0 me I would prefer the sword.
        - 0 item add _blunt_sword 1
        - 0 quest intro complete
    conversation:
        script:
            - 0 out I'm sorry I'm a little busy. Please come back later.

