meta:
    name: intro
    description: |
        this is the first quest in goldiriath
        
requirements: []
triggers: []

stages:
    entry:
        script: 
        - 0 note You wake up, but you do not remember how you got here. Maybe you should have a look around.
        triggers:
            ground_flour_start:
                - location goldiriath:1362:114:1028 2
    ground_flour_start:
        script: 
        - 0 out innkeeper Oh, good you're awake,
        - 20 out innkeeper Come and talk to me.
        - 0 zap ground_flour_stasis
    ground_flour_stasis:
        triggers:
            try_to_leave:
                - location goldiriath:1368:114:1038 3
    try_to_leave:
        script:
        - 0 command tp <player> 1362 114 1028
        - 5 out innkeeper Come talk to me before leaving
        - 0 zap ground_flour_stasis
    hay:
        script: []    
    gear:
        script: []
    complete:
        script:
         - 0 xp add 50
         - 0 note quest complete, congratulations
    cancel:
        script: []
